MODEL:
  TYPE: "SL_UDA_Segmentor"
  BACKBONE:
    # TYPE: "R-DL-101-C1-C5-FREEZEBN"
    TYPE: "MiT-B5"
    PRETRAINED: True
  DECODER:
    # TYPE: "DeepLabV2Dedoder"
    TYPE: "SegFormerDecoder"
  PREDICTOR:
    TYPE: "UpsamplePredictor"
    NUM_CLASSES: 2
    LOSS: "CrossEntropy"
  DISCRIMINATOR:
    LAMBDA_KLDREG_WEIGHT: 0.1
    LAMBDA_ENTROPY_WEIGHT: 3.0
TRAIN:
  ITER_VAL: 40
  EPOCHES: 10
  OPTIMIZER: "Adam"
  LR: 0.000025
  BATCHSIZE: 6
  ITER_REPORT: 10
  SIZE: [512,512]
  SAVE_ALL: False
  SCHEDULER: "CosineAnnealingLR_with_Restart"
  COSINEANNEALINGLR:
    T_MAX: 3
    T_MULT: 1.0
  MULTI_SCALE: True
  SCALES: [0.75, 1, 1.25]
DATASET:
  TYPE: "PolypWLIDataset"
  ANNS: "data/wli_train.json"
  IMAGEDIR: "/home/admin_mcn/namkd/polyp_data/WLI"
  USE_AUG: True
  USE_RANDAUG: True
  VAL:
    TYPE: "PolypBLIDataset"
    ANNS: "data/bli_val.json"
    IMAGEDIR: "/home/admin_mcn/namkd/polyp_data/BLI"
    # TYPE: "PolypWLIDataset"
    # ANNS: "data/wli_train.json"
    # IMAGEDIR: "/home/admin_mcn/namkd/polyp_data/WLI"
    RESIZE_SIZE: [512,512]
  TARGET:
    TYPE: "PolypBLIDataset"
    ANNS: "data/bli_train.json"
    IMAGEDIR: "/home/admin_mcn/namkd/polyp_data/BLI"
    PSEUDO_SIZE: [512, 512]
    # PSEUDO_SIZE: [600, 900]
    PSEUDO_PL: "IAST"
    PSEUDO_PL_ALPHA: 0.25
    PSEUDO_PL_GAMMA: 8.0
    PSEUDO_LOSS_WEIGHT: 1.0
    SOURCE_LOSS_WEIGHT: .0
    PSEUDO_PREV_UPDATE: True
TEST:
  # USE_MST: True
  # RESIZE_SIZE: [[1024, 512], [1280, 640], [1536, 768], [1800, 900], [2048, 1024]]

  RESIZE_SIZE: [[512,512]]
  # VISUALIZE: True
  # VISUALIZE_DIR: '/home/admin_mcn/namkd/rnd-domain-adaptation/results/visualize/polyp_0904/visualize'

  # RESIZE_SIZE: [[2048, 1024]]
  # EXTRACT_CONFUSION_MATRIX: True

  # RESIZE_SIZE: [[2048, 1024]]
  # VISUALIZE: True
  # VISUALIZE_DIR: '/home/nav/namkd/rnd-domain-adaptation/results/visualize/test_visualize/sl_fft_fix_loss_1311'
WORK_DIR: "log/gta5/sl_2"
